name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Deploy to server via SSH and perform multiple steps
            - name: Deploy and build on server
              uses: appleboy/ssh-action@v0.1.8
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      # Step 1: Navigate to the project folder
                      cd ~/Agrifarm-landing-page

                      # Step 2: Pull latest changes from the Git repository
                      git pull

                      # Step 3: Rebuild compose
                      docker-compose up --build -d
